### ISSUE TITLE
getOrdersHist returns buy and sell token with same token

### ISSUE THREAD

**Issue by CatScan-crypt** [DeversiFi/dvf-client-js#77]
api: 'https://api.deversifi.com'
file: getOrdersHist

response :
...
symbol: "ZRX:ETH"
tokenBuy: "ETH"
tokenSell: "ETH"
...

getOrders is fine -

... 
symbol: "ZRX:ETH"
tokenBuy: "ETH"
tokenSell: "ZRX"
...

**Comment by CatScan-crypt** [comment]
weirdly fixed it self :)

**Comment by AliMeer** [comment]
Seems fine, let me know if you still face issues.

<img width="483" alt="orderHistory" src="https://user-images.githubusercontent.com/7535475/83982041-061d0e00-a91b-11ea-8c43-fa96c0f06ac6.png">
