### ISSUE TITLE
ReferenceError: starkPrivKey is not defined

### ISSUE THREAD

**Issue by CatScan-crypt** [DeversiFi/dvf-client-js#86]
hello🤗 

tried " const starkPrivKey = ethPrivKey " and got 

😣 "error":"ETH_STARKKEY_NOT_MATCHED"

where can i find my starkPrivKey please 😇 ?  

tried- 

const starkPrivKey = dvf.stark.createPrivateKey()

got 

"ETH_STARKKEY_NOT_MATCHED"

**Comment by CatScan-crypt** [comment]
OK so after 3 days of testing, i see that you can't use metamusk or any other external wallet unless its ledger or raw private key if you want to develop . you cant even open an account from the site and than start to develop on it. I hope that in the future it will change, till than this is an irrelevant issue.

**Comment by AliMeer** [comment]
@CatScan-crypt This is a use case we are planning to implement soon. If you have the private key you are using on MetaMask then it is possible to create an account from the online platform and use it via the dvf client library. To achieve this you will need to get the backup file from the online platform and retrieve the stark private key from it and add it to the config as you would when using the src/examples.

**Comment by CatScan-crypt** [comment]
Great!
thanks @AliMeer.
i will test this and gladly add an example as a content in README.md if it's ok by you🙏.

**Comment by CatScan-crypt** [comment]
@AliMeer i unsuccessfully tried to pass all the parameters that looks like a private key as "STARK_PRIVATE_KEY" in config,  
can you tell me what parameter to pass please and what is the JSON object name?

> Trading key json format
{
   "version": 3,
   "id": "",
   "address": "",
   "crypto": {
      "ciphertext": "",
      "cipherparams": {
         "iv": ""
      },
      "cipher": "",
      "kdf": "",
      "kdfparams": {
         "0": 0,
         "dklen": 0,
         "salt": "",
         "n": 0
      },
      "mac": ""
   }
}

**Comment by blaaaaaaa** [comment]
hi, I try to submit an order via dvf-client-js. how do I obtain starkPrivKey? if I use starkPrivKey = dvf.stark.createPrivateKey() before it will still throw error: ETH_STARKKEY_NOT_MATCHED. same if I use starkPrivKey = ethPrivKey.
