### ISSUE TITLE
creating a backup file in app.deversifi.com changes  const starkPrivKey value 

### ISSUE THREAD

**Issue by CatScan-crypt** [DeversiFi/dvf-client-js#94]
After creating the trading key backup file, this message appears:

"error":"ETH_STARKKEY_NOT_MATCHED"

Please correct me if i'm wrong but stark private key value changes to an encrypted key 
that can only be decrypted  by my password i gave when creating this backup.

@AliMeer in issue 86# you mentioned  about this subject, that: 
"retrieve the stark private key from it and add it to the config",
But this file doesn't contain any value with this parameter, and iv'e tried to pass
every value from that file and it didn't work,
if you have any example for me it would be a blessing 🙏 thank you

**Comment by plutoegg** [comment]
The file is an Ethereum keystore file, and can be decrypted to retrieve the private key. 

You can do this for example using the MyCrypto Desktop app, or using this util in node.js

https://github.com/ethereumjs/keythereum

What you are looking for is just the private key as a hex string

**Comment by CatScan-crypt** [comment]
🧐 haha it works!
used myCrypto to decrypt sign message 
so the real issue here was my lack of understanding of crypto 🙈


1. my config file

{
  "INFURA_PROJECT_ID": "",
  "ETH_PRIVATE_KEY": "",
   "STRAK_PRIVATE_KEY": "",
  "account": {
    "address": "",
    "privateKey": ""
  }
}

2. 
export in examples\helpers\loadFromEnvOrConfig this---->  STARK_PRIVATE_KEY: getConfigVar('STARK_PRIVATE_KEY', config)

3. 
import to the examples --> const starkPrivKey=envVars.ETH_STRAK_PRIVATE_KEY

thank you @AliMeer 🎉
